### PR TITLE
Generic type Repository wrapper

### PR DESCRIPTION
**Pull request by Fs02**
- Simple wrapper to provide type safety to repository
- Rename record/records to be entity/entities, because the new generic repository is named as EntityRepository

### CODE REVIEW

**Comment by Fs02** [comment]
Hi @slashformotion, I'm glad that you are interested in this, this will be merged soon and support for `go-rel/reltest` will also follow. the plan is to release this overall changes within this week or next week

if you've any feedback or improvement idea, let me know

**Comment by slashformotion** [comment]
for a cleaner git history you should probably not merge master into anything, you should rebase
image
see this https://www.theserverside.com/blog/Coffee-Talk-Java-News-Stories-and-Opinions/How-to-Git-rebase-a-branch-to-master-example

**Comment by Fs02** [comment]
I'm using squash merge, which have the same result as rebase with with much more cleaner commit history
image

(not to mention, it's easier to resolve even the worst conflict using merge commit)

**Comment by Fs02** [comment]
also, with squash merge, there's no need to enable "allow force-push", which I'm very against with 🙈

**Comment by slashformotion** [comment]
interesting , I will look into it

**Pull request merged**
