### PR TITLE
fix issue #92 godoc on struct methods not on interface methods

### PR DESCRIPTION
**Pull request by mhewedy**

### CODE REVIEW

**Comment by Fs02** [comment]
Some function still missing the documentation (Adapter, Instrumentation, InsertAll, MustInsertAll), can you add that as well? thanks

**Comment by mhewedy** [comment]
The struct methods doesn't have documentation. Howerver I will try add my
own documentations, or if you like you can provide and I will add.

Thank you.

**Comment by Fs02** [comment]
Feel free to add your own documentation

**Comment by mhewedy** [comment]
sorry for the delay, I am a little bit busy these days. I will make sure I complete the PR soon.

**Comment by Fs02** [comment]
any news on this @mhewedy ?

**Comment by Fs02** [comment]
closed for inactivity, replaced by #131

**Comment by mhewedy** [comment]
> closed for inactivity, replaced by #131

Sorry for not having a a time window for it

**Pull request closed without merging**
