### PR TITLE
Add alternative soft delete scheme

### PR DESCRIPTION
**Pull request by lafriks**
Allows to use alternative soft delete scheme with boolean field `Deleted`. When record is deleted it will update `Deleted` to true and if there is `UpdatedAt` field it will also update it with deletion timestamp.

Sample:

```go
type Test struct {
  ID int64
  Name string
  CreatedAt time.Time
  UpdatedAt *time.Time
  Deleted bool
}
```

### CODE REVIEW

**Comment by lafriks** [comment]
Microsoft Entity Framework uses `IsDeleted` - https://docs.microsoft.com/en-us/ef/core/querying/filters

My personal motivation is that I would add `deleted` column to most of the indexes as second column as that helps to speed up things for large databases and to not bloat index it's better to have bool/bit column for this.

**Comment by lafriks** [comment]
Added also to have option to use both deleted and deleted_at in same table

**Comment by lafriks** [comment]
Would it be possible to merge it anyway so I can start using it? 😅

**Comment by Fs02** [comment]
haha
now built is success, let me merge and tag new version in master

**Pull request merged**
